"""Add recommendations table

Revision ID: 0d5b05b2959d
Revises: ab728e57747e
Create Date: 2025-11-13 17:54:39.575404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0d5b05b2959d'
down_revision: Union[str, Sequence[str], None] = 'ab728e57747e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('recommended_grade_level', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('current_usage', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('example_sentence', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ADOPTED', 'NOT_USED', name='recommendationstatus'), nullable=False),
    sa.Column('recommended_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_document_id'), 'recommendations', ['document_id'], unique=False)
    op.create_index(op.f('ix_recommendations_student_id'), 'recommendations', ['student_id'], unique=False)
    op.alter_column('analysis_results', 'grade_distribution',
               existing_type=None,
               nullable=True)
    op.alter_column('analysis_results', 'challenging_words',
               existing_type=None,
               nullable=True)
    op.alter_column('analysis_results', 'word_details',
               existing_type=None,
               nullable=True)
    op.alter_column('documents', 'error_message',
               existing_type=None,
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('grade_words', 'definition',
               existing_type=None,
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('grade_words', 'example',
               existing_type=None,
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('students', 'notes',
               existing_type=None,
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'notes',
               existing_type=sa.Text(),
               type_=None,
               existing_nullable=True)
    op.alter_column('grade_words', 'example',
               existing_type=sa.Text(),
               type_=None,
               existing_nullable=True)
    op.alter_column('grade_words', 'definition',
               existing_type=sa.Text(),
               type_=None,
               existing_nullable=False)
    op.alter_column('documents', 'error_message',
               existing_type=sa.Text(),
               type_=None,
               existing_nullable=True)
    op.alter_column('analysis_results', 'word_details',
               existing_type=None,
               nullable=False)
    op.alter_column('analysis_results', 'challenging_words',
               existing_type=None,
               nullable=False)
    op.alter_column('analysis_results', 'grade_distribution',
               existing_type=None,
               nullable=False)
    op.drop_index(op.f('ix_recommendations_student_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_document_id'), table_name='recommendations')
    op.drop_table('recommendations')
    # ### end Alembic commands ###
