"""add vocabulary history and word usage tracking tables

Revision ID: 765f1e7b251b
Revises: 0d5b05b2959d
Create Date: 2025-11-13 19:00:10.494345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '765f1e7b251b'
down_revision: Union[str, Sequence[str], None] = '0d5b05b2959d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocabulary_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('student_id', sa.Integer(), nullable=False),
        sa.Column('document_id', sa.Integer(), nullable=False),
        sa.Column('analysis_result_id', sa.Integer(), nullable=False),
        sa.Column('analyzed_at', sa.DateTime(), nullable=False),
        sa.Column('average_grade_level', sa.Float(), nullable=True),
        sa.Column('total_words', sa.Integer(), nullable=False),
        sa.Column('unique_words', sa.Integer(), nullable=False),
        sa.Column('grade_distribution', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis_results.id'], ),
        sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
        sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_history_analysis_result_id'), 'vocabulary_history', ['analysis_result_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_history_analyzed_at'), 'vocabulary_history', ['analyzed_at'], unique=False)
    op.create_index(op.f('ix_vocabulary_history_document_id'), 'vocabulary_history', ['document_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_history_student_id'), 'vocabulary_history', ['student_id'], unique=False)
    op.create_table('word_usage_tracking',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('recommendation_id', sa.Integer(), nullable=False),
        sa.Column('document_id', sa.Integer(), nullable=False),
        sa.Column('used', sa.Boolean(), nullable=False),
        sa.Column('detected_at', sa.DateTime(), nullable=False),
        sa.Column('occurrence_count', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
        sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_usage_tracking_document_id'), 'word_usage_tracking', ['document_id'], unique=False)
    op.create_index(op.f('ix_word_usage_tracking_recommendation_id'), 'word_usage_tracking', ['recommendation_id'], unique=False)
    op.alter_column('documents', 'error_message',
               existing_type=None,
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('grade_words', 'definition',
               existing_type=None,
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('grade_words', 'example',
               existing_type=None,
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('recommendations', 'current_usage',
               existing_type=None,
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('recommendations', 'context',
               existing_type=None,
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('recommendations', 'example_sentence',
               existing_type=None,
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('recommendations', 'rationale',
               existing_type=None,
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('recommendations', 'status',
               existing_type=None,
               nullable=True)
    op.alter_column('students', 'notes',
               existing_type=None,
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'notes',
               existing_type=sa.Text(),
               type_=None,
               existing_nullable=True)
    op.alter_column('recommendations', 'status',
               existing_type=None,
               nullable=False)
    op.alter_column('recommendations', 'rationale',
               existing_type=sa.Text(),
               type_=None,
               existing_nullable=True)
    op.alter_column('recommendations', 'example_sentence',
               existing_type=sa.Text(),
               type_=None,
               existing_nullable=True)
    op.alter_column('recommendations', 'context',
               existing_type=sa.Text(),
               type_=None,
               existing_nullable=True)
    op.alter_column('recommendations', 'current_usage',
               existing_type=sa.Text(),
               type_=None,
               existing_nullable=True)
    op.alter_column('grade_words', 'example',
               existing_type=sa.Text(),
               type_=None,
               existing_nullable=True)
    op.alter_column('grade_words', 'definition',
               existing_type=sa.Text(),
               type_=None,
               existing_nullable=False)
    op.alter_column('documents', 'error_message',
               existing_type=sa.Text(),
               type_=None,
               existing_nullable=True)
    op.drop_index(op.f('ix_word_usage_tracking_recommendation_id'), table_name='word_usage_tracking')
    op.drop_index(op.f('ix_word_usage_tracking_document_id'), table_name='word_usage_tracking')
    op.drop_table('word_usage_tracking')
    op.drop_index(op.f('ix_vocabulary_history_student_id'), table_name='vocabulary_history')
    op.drop_index(op.f('ix_vocabulary_history_document_id'), table_name='vocabulary_history')
    op.drop_index(op.f('ix_vocabulary_history_analyzed_at'), table_name='vocabulary_history')
    op.drop_index(op.f('ix_vocabulary_history_analysis_result_id'), table_name='vocabulary_history')
    op.drop_table('vocabulary_history')
    # ### end Alembic commands ###
