/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/auth/me": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Current Educator
     * @description Get current authenticated educator information
     *
     *     This endpoint:
     *     1. Verifies JWT token (via get_current_user dependency)
     *     2. Gets or creates educator record in database
     *     3. Returns educator information
     *
     *     Protected endpoint - requires valid JWT token in Authorization header.
     *
     *     Returns:
     *         EducatorPublic: Current educator's information
     */
    get: operations["get_current_educator_api_auth_me_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/auth/logout": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Logout
     * @description Logout endpoint (placeholder)
     *
     *     In Supabase, logout is handled client-side by clearing the session.
     *     This endpoint exists for consistency and can be used for:
     *     - Logging logout events
     *     - Invalidating refresh tokens (if needed)
     *     - Analytics
     *
     *     Returns:
     *         Success message
     */
    post: operations["logout_api_auth_logout_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/auth/verify": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Verify Token
     * @description Verify JWT token validity
     *
     *     Simple endpoint to check if a token is valid.
     *     Useful for frontend to verify authentication status.
     *
     *     Returns:
     *         User information if token is valid
     */
    get: operations["verify_token_api_auth_verify_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/s3/upload-url": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Get Upload Url
     * @description Generate a presigned URL for uploading a document to S3
     *
     *     This endpoint:
     *     1. Verifies the educator owns the student
     *     2. Generates a unique S3 key for the document
     *     3. Creates a presigned URL for direct browser upload
     *     4. Returns the URL and S3 key (save the key in document metadata)
     *
     *     The frontend should:
     *     1. Call this endpoint to get presigned URL and S3 key
     *     2. Upload file directly to S3 using PUT request with presigned URL
     *     3. Create document record in database with the returned S3 key
     *
     *     Protected endpoint - requires valid JWT token.
     *
     *     Args:
     *         request: Upload URL request with student_id, filename, content_type
     *         user: Current authenticated user (injected by dependency)
     *         session: Database session (injected by dependency)
     *
     *     Returns:
     *         UploadUrlResponse: Presigned URL and S3 key
     *
     *     Raises:
     *         HTTPException 401: If not authenticated
     *         HTTPException 403: If educator doesn't own the student
     *         HTTPException 404: If student not found
     *         HTTPException 500: If S3 configuration error
     */
    post: operations["get_upload_url_api_s3_upload_url_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/s3/download-url": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Get Download Url
     * @description Generate a presigned URL for downloading a document from S3
     *
     *     This endpoint:
     *     1. Extracts educator and student IDs from the S3 key
     *     2. Verifies the educator owns the student
     *     3. Generates a presigned URL for downloading the file
     *
     *     Protected endpoint - requires valid JWT token.
     *
     *     Args:
     *         request: Download URL request with S3 key
     *         user: Current authenticated user (injected by dependency)
     *         session: Database session (injected by dependency)
     *
     *     Returns:
     *         DownloadUrlResponse: Presigned URL for download
     *
     *     Raises:
     *         HTTPException 401: If not authenticated
     *         HTTPException 403: If educator doesn't own the document
     *         HTTPException 404: If educator or student not found
     *         HTTPException 400: If S3 key format is invalid
     *         HTTPException 500: If S3 configuration error
     */
    post: operations["get_download_url_api_s3_download_url_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/s3/health": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * S3 Health Check
     * @description S3 health check endpoint
     *
     *     Verifies that:
     *     - S3 credentials are configured
     *     - S3 bucket exists and is accessible
     *
     *     Returns:
     *         dict: Health status
     *
     *     Raises:
     *         HTTPException 500: If S3 is not properly configured
     */
    get: operations["s3_health_check_api_s3_health_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/students": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Students
     * @description Get all students for the current educator
     *
     *     Protected endpoint - requires valid JWT token.
     *     Returns only students belonging to the authenticated educator.
     *
     *     Args:
     *         user: Current authenticated user from JWT
     *         session: Database session
     *
     *     Returns:
     *         list[StudentPublic]: List of students for this educator
     */
    get: operations["get_students_api_students_get"]
    put?: never
    /**
     * Create Student
     * @description Create a new student profile
     *
     *     This endpoint:
     *     1. Verifies JWT token and gets educator from email
     *     2. Validates student data (name, grade_level 6-12)
     *     3. Creates student record linked to educator
     *     4. Returns created student
     *
     *     Protected endpoint - requires valid JWT token in Authorization header.
     *
     *     Args:
     *         student_data: Student information (name, grade_level, reading_level, notes)
     *         user: Current authenticated user from JWT
     *         session: Database session
     *
     *     Returns:
     *         StudentPublic: Created student information
     *
     *     Raises:
     *         HTTPException 401: If authentication fails
     *         HTTPException 404: If educator not found
     *         HTTPException 422: If validation fails (e.g., invalid grade level)
     */
    post: operations["create_student_api_students_post"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/students/{student_id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Student
     * @description Get a specific student by ID
     *
     *     Protected endpoint - verifies the student belongs to the authenticated educator.
     *
     *     Args:
     *         student_id: Student database ID
     *         user: Current authenticated user from JWT
     *         session: Database session
     *
     *     Returns:
     *         StudentPublic: Student information
     *
     *     Raises:
     *         HTTPException 404: If student not found or doesn't belong to educator
     */
    get: operations["get_student_api_students__student_id__get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Root
     * @description Root endpoint
     */
    get: operations["root__get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/health": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health Check
     * @description Health check endpoint
     */
    get: operations["health_check_health_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/educators": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Educators
     * @description Example endpoint: Get all educators (limited)
     *
     *     This demonstrates SQLModel integration with FastAPI.
     *     In production, this would be protected and filtered by auth.
     */
    get: operations["get_educators_api_educators_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/educators/{educator_id}/students": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Educator Students
     * @description Example endpoint: Get all students for an educator
     *
     *     In production, this would verify JWT and ensure educator owns these students.
     */
    get: operations["get_educator_students_api_educators__educator_id__students_get"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * DownloadUrlRequest
     * @description Request to generate a presigned download URL
     * @example {
     *       "s3_key": "educators/1/students/5/documents/uuid-essay.pdf"
     *     }
     */
    DownloadUrlRequest: {
      /**
       * S3 Key
       * @description S3 object key from document metadata
       */
      s3_key: string
    }
    /**
     * DownloadUrlResponse
     * @description Response containing presigned download URL
     * @example {
     *       "expires_in": 3600,
     *       "presigned_url": "https://bucket.s3.amazonaws.com/path?signature=..."
     *     }
     */
    DownloadUrlResponse: {
      /**
       * Presigned Url
       * @description Presigned URL for downloading the file via GET request
       */
      presigned_url: string
      /**
       * Expires In
       * @description URL expiration time in seconds
       */
      expires_in: number
    }
    /**
     * EducatorPublic
     * @description Public educator data for API responses
     */
    EducatorPublic: {
      /** Id */
      id: number
      /** Email */
      email: string
      /** Name */
      name: string
      /** School */
      school: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][]
    }
    /**
     * StudentCreate
     * @description Data required to create a student
     */
    StudentCreate: {
      /** Name */
      name: string
      /** Grade Level */
      grade_level: number
      /** Reading Level */
      reading_level?: string | null
      /** Notes */
      notes?: string | null
    }
    /**
     * StudentPublic
     * @description Public student data for API responses
     */
    StudentPublic: {
      /** Id */
      id: number
      /** Educator Id */
      educator_id: number
      /** Name */
      name: string
      /** Grade Level */
      grade_level: number
      /** Reading Level */
      reading_level: string | null
      /** Notes */
      notes: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /**
     * UploadUrlRequest
     * @description Request to generate a presigned upload URL
     * @example {
     *       "content_type": "application/pdf",
     *       "filename": "essay.pdf",
     *       "student_id": 5
     *     }
     */
    UploadUrlRequest: {
      /**
       * Student Id
       * @description ID of the student the document belongs to
       */
      student_id: number
      /**
       * Filename
       * @description Original filename
       */
      filename: string
      /**
       * Content Type
       * @description MIME type (e.g., application/pdf, text/plain)
       */
      content_type: string
    }
    /**
     * UploadUrlResponse
     * @description Response containing presigned upload URL
     * @example {
     *       "expires_in": 3600,
     *       "presigned_url": "https://bucket.s3.amazonaws.com/path?signature=...",
     *       "s3_key": "educators/1/students/5/documents/uuid-essay.pdf"
     *     }
     */
    UploadUrlResponse: {
      /**
       * Presigned Url
       * @description Presigned URL for uploading the file via PUT request
       */
      presigned_url: string
      /**
       * S3 Key
       * @description S3 object key - save this to document metadata
       */
      s3_key: string
      /**
       * Expires In
       * @description URL expiration time in seconds
       */
      expires_in: number
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  get_current_educator_api_auth_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["EducatorPublic"]
        }
      }
    }
  }
  logout_api_auth_logout_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
    }
  }
  verify_token_api_auth_verify_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
    }
  }
  get_upload_url_api_s3_upload_url_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["UploadUrlRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["UploadUrlResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_download_url_api_s3_download_url_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["DownloadUrlRequest"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["DownloadUrlResponse"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  s3_health_check_api_s3_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
    }
  }
  get_students_api_students_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["StudentPublic"][]
        }
      }
    }
  }
  create_student_api_students_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["StudentCreate"]
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["StudentPublic"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_student_api_students__student_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        student_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["StudentPublic"]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  root__get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
    }
  }
  health_check_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
    }
  }
  get_educators_api_educators_get: {
    parameters: {
      query?: {
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["EducatorPublic"][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_educator_students_api_educators__educator_id__students_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        educator_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
}
